In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [3]:
# Create a list
lst = list(range(16))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [4]:
# Creating a numpy array from a Python list
x = np.array(lst)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
# numpy arrays contain elements that are all of the same type
# if types do not match, numpy upcasts whenever possible (EG: integers are upcasted to floats below)
x = np.array([3.14, 4, 2, 3])
print(x)
print(type(x[0]))

[3.14 4.   2.   3.  ]
<class 'numpy.float64'>


In [6]:
# set the data type of the array to float using dtype
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [7]:
# multidimensional array using list of lists
x = np.array([[1,2,3,4],
              [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
x.shape

(2, 4)

In [9]:
# multidimensional list using list comprehensions
x = np.array([range(i, i+10) for i in range(1,10)])
print(x)
print()
print(x.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]

(9, 10)


In [10]:
# numpy array filled with zeros; dtype=float by default
zeros = np.zeros((10,10))
print(zeros)
print()
print(zeros.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

(10, 10)


In [11]:
# numpy array with 0's and int as data type
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Create a 3 by 5 array of floating point values (default) filled with 1's 
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# A 4 by 4 identity matrix with int as data type
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [14]:
# Create a 3x5 array filled with the value 100
np.full((3, 5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [15]:
# Create an array that starts at 0, ends at 50, stepping by 5 each time
# similar behaviour as python's range() function
# NOTE - the start and stop values are as follows: [start, stop)
np.arange(0, 51, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [16]:
# Create an array of 50 values evenly spaced between 0 and 10
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
# a 3 by 3 array of uniformly distributed random values between 0 and 1
np.random.random((3,5))

array([[0.90368996, 0.17903428, 0.74208733, 0.35143314, 0.19912094],
       [0.6776964 , 0.56963247, 0.98653899, 0.08367442, 0.89137202],
       [0.60283988, 0.4788134 , 0.38414484, 0.03172513, 0.25524699]])

In [18]:
# a 3 by 3 array of normally distributed random values with a mean of 0 and a standard deviation of 1
np.random.normal(0, 1, (3, 3))

array([[-8.47185306e-01,  5.69792724e-01, -3.02630047e-01],
       [ 8.73446950e-02,  2.04892549e+00,  2.38687806e+00],
       [-2.88961332e-02, -1.40374747e-03,  1.72496894e+00]])

In [19]:
#  A 4 by 4 array of random integers in the interval [0, 50)
np.random.randint(0, 50, (4, 4))

array([[10, 37, 28, 23],
       [ 5, 45, 22, 26],
       [40,  2, 41,  8],
       [27, 30, 22,  1]])