In [2]:
import numpy as np

In [3]:
# 1D array - 10 evenly spaced numbers from 1-100
x = np.linspace(0,100,10)
x

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Indexing Numpy Arrays

In [4]:
# get the SECOND element from x
x[1]

11.11111111111111

In [5]:
# get the FOURTH element from x
x[3]

33.33333333333333

In [6]:
# get the LAST element
x[-1]

100.0

In [7]:
# get the THIRD FROM LAST element from x
x[-3]

77.77777777777777

In [8]:
# set the value at index 2 to 3000 (for Tony Stark)
x[2] = 3000
x

array([   0.        ,   11.11111111, 3000.        ,   33.33333333,
         44.44444444,   55.55555556,   66.66666667,   77.77777778,
         88.88888889,  100.        ])

In [10]:
# 2D array - numbers from 1-10 within a 5 by 6 matrix
y = np.random.randint(10, size=(5,6))
y

array([[3, 8, 8, 7, 1, 1],
       [0, 4, 6, 9, 2, 9],
       [3, 2, 1, 3, 6, 6],
       [1, 6, 6, 0, 1, 3],
       [8, 1, 2, 3, 7, 5]])

In [12]:
# so y has 5 rows, 6 columns
y.shape

(5, 6)

In [10]:
# get the element from row 2, column 4
y[1,3]

4

In [11]:
# get the last element from row 4
y[3,-1]

6

In [12]:
# set the value at row 1, column 3 to 12
y[0, 2] = 12
y

array([[ 3,  0, 12,  8,  2,  2],
       [ 7,  7,  1,  4,  5,  3],
       [ 2,  0,  5,  3,  0,  8],
       [ 8,  2,  0,  7,  5,  6],
       [ 8,  2,  1,  1,  2,  3]])

### Slicing Numpy Arrays

To slice an array 'arr', we follow the same convention from that of Python ... which is arr[start:stop:step] ... by default step=1

#### 1D Array

In [13]:
x = np.random.randint(10, size=(20))
x

array([6, 4, 1, 0, 3, 5, 2, 6, 6, 7, 9, 9, 3, 2, 2, 0, 5, 1, 8, 6])

In [14]:
# same as x itself ... this results in the all the elements in x
x[:]

array([6, 4, 1, 0, 3, 5, 2, 6, 6, 7, 9, 9, 3, 2, 2, 0, 5, 1, 8, 6])

In [15]:
# elements from index 5 till the end of the array
x[5:]

array([5, 2, 6, 6, 7, 9, 9, 3, 2, 2, 0, 5, 1, 8, 6])

In [16]:
# elements from the beginning to index 16 ... stop=num-1 as it is not inclusive
x[:16]

array([6, 4, 1, 0, 3, 5, 2, 6, 6, 7, 9, 9, 3, 2, 2, 0])

In [17]:
# elements from index 3 to 14
x[3:15]

array([0, 3, 5, 2, 6, 6, 7, 9, 9, 3, 2, 2])

In [18]:
# every OTHER (because step size is 2) element from index 2 to 14 
x[2:15:2]

array([1, 3, 2, 6, 9, 3, 2])

In [19]:
# every THIRD element from the whole array
x[::3]

array([6, 0, 2, 7, 3, 0, 8])

In [20]:
# reverse the array 
x[::-1]

array([6, 8, 1, 5, 0, 2, 2, 3, 9, 9, 7, 6, 6, 2, 5, 3, 0, 1, 4, 6])

#### Multidimensional Arrays

In [21]:
y

array([[ 3,  0, 12,  8,  2,  2],
       [ 7,  7,  1,  4,  5,  3],
       [ 2,  0,  5,  3,  0,  8],
       [ 8,  2,  0,  7,  5,  6],
       [ 8,  2,  1,  1,  2,  3]])

In [22]:
# first 2 rows, first 2 columns
y[:2, :2]

array([[3, 0],
       [7, 7]])

In [23]:
# third row onwards, fourth column onwards
y[2:, 3:]

array([[3, 0, 8],
       [7, 5, 6],
       [1, 2, 3]])

In [24]:
# select rows 2-4, and columns 2 and 3
y[1:4, 1:3]

array([[7, 1],
       [0, 5],
       [2, 0]])

In [25]:
# all rows, but every other column from y
y[:, ::2]

array([[ 3, 12,  2],
       [ 7,  1,  5],
       [ 2,  5,  0],
       [ 8,  0,  5],
       [ 8,  1,  2]])

### Reshaping Numpy Arrays

In [26]:
# create an array of 20 values
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
# using reshape(), turn a into a 4 rows by 5 columns array
a.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
# turn 'a' into a 10 rows by 2 columns array
a.reshape(10, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

### Concatenating (joining) Numpy Arrays

#### Concatenate 1D arrays

In [47]:
a = np.arange(1,11)
b = np.arange(11, 21)

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [48]:
# using np.concatenate() to concatenate arrays a and b
c = np.concatenate([a,b])
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
c.shape

(20,)

In [50]:
# 2D array
c.reshape(20,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [51]:
d = np.arange(21,31)
e = np.arange(31, 41)

print(d)
print(e)

[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]


In [52]:
# concatenate more than 2 arrays ... in this case, concatenate a, b, d and e 
f = np.concatenate([a,b,d,e])
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

#### Concatenate 2D arrays

In [53]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])

In [54]:
# concatenate a and b over axis = 0; arrays being concatenated should have the same dimensions
np.concatenate((a, b), 0)

array([[ 0,  1,  3],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [55]:
# concatenate a and b over axis = 1
np.concatenate((a, b), 1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [60]:
x = np.array([1,2,3,4])

In [56]:
# arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

array([6, 4, 1, 0, 3, 5, 2, 6, 6, 7, 9, 9, 3, 2, 2, 0, 5, 1, 8, 6])

In [57]:
y

array([[ 3,  0, 12,  8,  2,  2],
       [ 7,  7,  1,  4,  5,  3],
       [ 2,  0,  5,  3,  0,  8],
       [ 8,  2,  0,  7,  5,  6],
       [ 8,  2,  1,  1,  2,  3]])

#### Array Spliting

In [13]:
x = [10, 20, 30, 40, 50, 60, 70, 80]

In [17]:
# split at index 2 and index 4
x1, x2, x3 = np.split(x, [2, 4])

In [18]:
x1

array([10, 20])

In [19]:
x2

array([30, 40])

In [21]:
x3

array([50, 60, 70, 80])

In [32]:
x = np.arange(16).reshape((4, 4))

In [29]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
# Split an array into multiple sub-arrays horizontally (column-wise)
np.hsplit(x, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [35]:
# Split an array into multiple sub-arrays vertically (row-wise).
np.vsplit(x, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]